spring:
  application:
    name: batch
  profiles:
    active: ${PROFILE}

data:
  tmdb:
    read-access-token: ${TMDB_READ_ACCESS_TOKEN}
    key: ${TMDB_KEY}
    base-url: https://api.themoviedb.org/3/discover
