server:
  port: 8080

spring:
  datasource:
    jdbc-url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}

  batch:
    datasource:
      jdbc-url: ${BATCH_DB_URL}
      driver-class-name: org.postgresql.Driver
      username: ${BATCH_DB_USERNAME}
      password: ${BATCH_DB_PASSWORD}
    jdbc:
      initialize-schema: never
    job:
      enabled: false
    schedule:
      tmdb: 0 0 1 * * * # 매일 새벽 1시
      sport-api: 0 0 1 * * * # 매일 새벽 1시

    flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: dev-redis-server
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    com.mopl: DEBUG