spring:
  datasource:
    jdbc-url: ${BUSINESS_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${BUSINESS_DB_USERNAME}
    password: ${BUSINESS_DB_PASSWORD}

  batch:
    datasource:
      jdbc-url: ${BATCH_DB_URL}
      driver-class-name: org.postgresql.Driver
      username: ${BATCH_DB_USERNAME}
      password: ${BATCH_DB_PASSWORD}
    jdbc:
      initialize-schema: never
    job:
      enabled: false
    schedule:
      tmdb: ${TMDB_SCHEDULE} # 매일 새벽 1시
      sport-api: ${SPORT_API_SCHEDULE} # 매일 새벽 1시

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
