name: Deploy Batch To EC2
on:
  push:
    branches:
      - main
      - deploy
    paths:
      - "src/**"
      - "build.gradle"
      - ".github/workflows/deploy-batch.yml"
      - "deploy/**"
      - "Dockerfile-prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 가져오기
        uses: actions/checkout@v4

      - name: JDK 21 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew clean build -x test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Batch Docker 이미지 생성
        run: docker build -t mopl-batch -f Dockerfile-prod .

      - name: Batch Docker 이미지에 Tag 붙이기
        run: docker tag mopl-batch ${{steps.login-ecr.outputs.registry}}/mopl/batch:latest

      - name: ECR에 Batch Docker 이미지 Push
        run: docker push ${{steps.login-ecr.outputs.registry}}/mopl/batch:latest

      - name: .env 파일 생성
        run: |
          cat > .env << EOF
          PROFILE=${{secrets.PROFILE}}
          
          # TMDB API
          TMDB_READ_ACCESS_TOKEN=${{secrets.TMDB_READ_ACCESS_TOKEN}}
          TMDB_KEY=${{secrets.TMDB_KEY}}
          TMDB_SCHEDULE=${{secrets.TMDB_SCHEDULE}}
          SPORT_API_SCHEDULE=${{secrets.SPORT_API_SCHEDULE}}
          
          # Business Database
          BUSINESS_DB_URL=${{secrets.BUSINESS_DB_URL}}
          BUSINESS_DB_USERNAME=${{secrets.BUSINESS_DB_USERNAME}}
          BUSINESS_DB_PASSWORD=${{secrets.BUSINESS_DB_PASSWORD}}
          
          # Batch Database
          BATCH_DB_URL=${{secrets.BATCH_DB_URL}}
          BATCH_DB_USERNAME=${{secrets.BATCH_DB_USERNAME}}
          BATCH_DB_PASSWORD=${{secrets.BATCH_DB_PASSWORD}}
          
          # Redis
          REDIS_HOST=${{secrets.REDIS_HOST}}
          REDIS_PORT=${{secrets.REDIS_PORT}}
          
          # Elasticsearch
          SPRING_ELASTIC_SERVERS=${{secrets.SPRING_ELASTIC_SERVERS}}
          
          # Prometheus
          PROMETHEUS_PUSHGATEWAY_URL=${{secrets.PROMETHEUS_PUSHGATEWAY_URL}}
          EOF

      - name: 압축하기
        run: |
          cp deploy/batch/appspec.yml ./appspec.yml
          cp -r deploy/batch/scripts ./scripts
          cp deploy/batch/docker-compose.prod.yml ./docker-compose.prod.yml
          tar -czvf $GITHUB_SHA.tar.gz \
            appspec.yml \
            .env \
            scripts \
            docker-compose.prod.yml

      - name: S3에 프로젝트 폴더 업로드 하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://mopl-deploy-4/batch/$GITHUB_SHA.tar.gz

      - name: CodeDeploy 배포 트리거
        run: |
          aws deploy create-deployment \
            --application-name mopl-batch \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name mopl-deploy-group-batch \
            --s3-location bucket=mopl-deploy-4,key=batch/$GITHUB_SHA.tar.gz,bundleType=tgz
